[project]
name = "20250927-aws-lambda-sample-zip"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aws-lambda-powertools[parser]>=3.20.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
